-- Coffee Map Merida: admin, social posts, cafe photos and hardened RLS.
-- Apply once with the Supabase SQL editor or CLI before deploying this version.

create extension if not exists pgcrypto;

alter table public.cafes add column if not exists status text not null default 'active';
alter table public.cafes add column if not exists address text;
alter table public.cafes add column if not exists last_verified_at timestamptz;
alter table public.cafes drop constraint if exists cafes_status_check;
alter table public.cafes add constraint cafes_status_check
check (status in ('active', 'needs_review', 'closed'));

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  cafe_id text references public.cafes(id) on delete set null,
  content text not null check (char_length(content) between 1 and 500),
  image_url text,
  status text not null default 'published'
    check (status in ('published', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cafe_photos (
  id uuid primary key default gen_random_uuid(),
  cafe_id text not null references public.cafes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid references public.posts(id) on delete set null,
  storage_path text not null,
  public_url text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  is_cover boolean not null default false,
  created_at timestamptz not null default now(),
  moderated_at timestamptz,
  moderated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists posts_user_id_idx on public.posts(user_id);
create index if not exists posts_cafe_id_idx on public.posts(cafe_id);
create index if not exists cafe_photos_status_idx on public.cafe_photos(status, created_at desc);
create index if not exists cafe_photos_cafe_id_idx on public.cafe_photos(cafe_id);
create index if not exists cafe_photos_user_id_idx on public.cafe_photos(user_id);
create index if not exists cafe_photos_post_id_idx on public.cafe_photos(post_id);
create index if not exists cafe_photos_moderated_by_idx on public.cafe_photos(moderated_by);
create index if not exists app_events_name_created_idx on public.app_events(event_name, created_at desc);
create index if not exists app_events_user_id_idx on public.app_events(user_id);

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'administrador'
  );
$$;

revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

alter table public.posts enable row level security;
alter table public.cafe_photos enable row level security;
alter table public.app_events enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
on public.profiles for select to authenticated using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert to authenticated
with check ((select auth.uid()) = id and role = 'usuario');

drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update to authenticated
using ((select auth.uid()) = id or (select private.is_admin()))
with check (
  (select private.is_admin())
  or ((select auth.uid()) = id and role = 'usuario')
);

drop policy if exists "cafes_select_authenticated" on public.cafes;
create policy "cafes_select_authenticated"
on public.cafes for select to authenticated
using (status = 'active' or (select private.is_admin()));

drop policy if exists "cafes_insert_authenticated" on public.cafes;
drop policy if exists "cafes_insert_admin" on public.cafes;
create policy "cafes_insert_admin"
on public.cafes for insert to authenticated with check ((select private.is_admin()));

drop policy if exists "cafes_update_admin" on public.cafes;
create policy "cafes_update_admin"
on public.cafes for update to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

drop policy if exists "cafes_delete_admin" on public.cafes;
create policy "cafes_delete_admin"
on public.cafes for delete to authenticated using ((select private.is_admin()));

drop policy if exists "posts_select_visible" on public.posts;
create policy "posts_select_visible"
on public.posts for select to authenticated
using (status = 'published' or user_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "posts_insert_own" on public.posts;
create policy "posts_insert_own"
on public.posts for insert to authenticated
with check (user_id = (select auth.uid()) and status = 'published');

drop policy if exists "posts_update_own_or_admin" on public.posts;
create policy "posts_update_own_or_admin"
on public.posts for update to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()))
with check ((select private.is_admin()) or (user_id = (select auth.uid()) and status = 'published'));

drop policy if exists "posts_delete_own_or_admin" on public.posts;
create policy "posts_delete_own_or_admin"
on public.posts for delete to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "cafe_photos_select_visible" on public.cafe_photos;
create policy "cafe_photos_select_visible"
on public.cafe_photos for select to authenticated
using (status = 'approved' or user_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "cafe_photos_insert_own" on public.cafe_photos;
create policy "cafe_photos_insert_own"
on public.cafe_photos for insert to authenticated
with check (
  user_id = (select auth.uid())
  and (status = 'pending' or (select private.is_admin()))
);

drop policy if exists "cafe_photos_moderate_admin" on public.cafe_photos;
create policy "cafe_photos_moderate_admin"
on public.cafe_photos for update to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));

drop policy if exists "cafe_photos_delete_owner_or_admin" on public.cafe_photos;
create policy "cafe_photos_delete_owner_or_admin"
on public.cafe_photos for delete to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "app_events_insert_own" on public.app_events;
create policy "app_events_insert_own"
on public.app_events for insert to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "app_events_select_admin" on public.app_events;
create policy "app_events_select_admin"
on public.app_events for select to authenticated using ((select private.is_admin()));

revoke all on public.posts, public.cafe_photos, public.app_events from anon;
grant select, insert, update, delete on public.posts, public.cafe_photos to authenticated;
grant select, insert on public.app_events to authenticated;
grant usage, select on sequence public.app_events_id_seq to authenticated;

-- Trigger functions are not RPC endpoints. Keep execution internal.
revoke all on function public.handle_new_user() from public, anon, authenticated;

-- Harden the legacy quota function only when upgrading a database that has it.
do $$
begin
  if to_regprocedure('public.reserve_google_api_usage(text,text,integer,integer)') is not null then
    execute 'revoke all on function public.reserve_google_api_usage(text, text, integer, integer) from public, anon, authenticated';
    execute 'grant execute on function public.reserve_google_api_usage(text, text, integer, integer) to service_role';
  end if;
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cafe-photos',
  'cafe-photos',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "cafe_photos_storage_read" on storage.objects;
create policy "cafe_photos_storage_read"
on storage.objects for select to authenticated
using (bucket_id = 'cafe-photos');

drop policy if exists "cafe_photos_storage_insert" on storage.objects;
create policy "cafe_photos_storage_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'cafe-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "cafe_photos_storage_delete" on storage.objects;
create policy "cafe_photos_storage_delete"
on storage.objects for delete to authenticated
using (
  bucket_id = 'cafe-photos'
  and ((storage.foldername(name))[1] = (select auth.uid())::text or (select private.is_admin()))
);

-- Promote the requested existing account without storing any password.
update public.profiles
set role = 'administrador', updated_at = now()
where id in (
  select id from auth.users where lower(email) = lower('marianalarag@outlook.com')
);
