-- Generated from verified reverse geocoding coordinates on 2026-09-12.
update public.cafes set nombre = 'Itzaes', address = 'Itzaes, Calle 30, Mérida, Yucatán, 97295, México', neighborhood = 'Mérida' where id = 'osm:node:6661240925';
update public.cafes set nombre = 'Origen Tostadores de Cafe', address = 'Calle 77 528, Mérida, Yuc', neighborhood = 'Centro' where id = 'osm:node:5432024842';
update public.cafes set nombre = 'Alma Cálida', address = 'Calle 75 539', neighborhood = 'Centro' where id = 'osm:node:13543569601';
update public.cafes set nombre = 'Orgánico Bar de Café & Cocina', address = 'Calle 62 582, Mérida', neighborhood = 'Centro' where id = 'osm:node:14007701947';
update public.cafes set nombre = 'Cafetería La Primera de San Cristóbal', address = 'Cafetería La Primera de San Cristóbal, Calle 50 A, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:4803875140';
update public.cafes set nombre = 'Expandio de leche pura de vaca', address = 'Expandio de leche pura de vaca, Calle 69, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:4316605490';
update public.cafes set nombre = 'El Gato Gordo', address = 'El Gato Gordo, Calle 70, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:10934459705';
update public.cafes set nombre = 'Manifesto', address = 'Manifesto, Calle 59, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:5411151722';
update public.cafes set nombre = 'Placer & Delirio', address = 'Calle 59', neighborhood = 'Centro' where id = 'osm:node:8263119752';
update public.cafes set nombre = 'Gloria Jean''s', address = 'Gloria Jean''s, Calle 59, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:9356763818';
update public.cafes set nombre = 'Bisquets Obregón', address = 'Calle 62', neighborhood = 'Centro' where id = 'osm:node:4293127692';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, 496, Calle 60, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:5670808327';
update public.cafes set nombre = 'The Italian coffee', address = 'Calle 62 499', neighborhood = 'Centro' where id = 'osm:node:9733620417';
update public.cafes set nombre = 'La abidia', address = 'Calle 62', neighborhood = 'Centro' where id = 'osm:node:9738766118';
update public.cafes set nombre = 'Central Mid', address = 'Central Mid, Calle 63, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:11287387069';
update public.cafes set nombre = 'Delicoffee cafetería', address = 'Delicoffee cafetería, Calle 65, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:12777074732';
update public.cafes set nombre = 'Maid Cafe', address = 'Maid Cafe, Calle 61, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:5850108186';
update public.cafes set nombre = 'Cafeteria Pop', address = 'Cafeteria Pop, Calle 57, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:4551562890';
update public.cafes set nombre = 'Cucu Bistro & Coffee', address = 'Calle 59 527C, Centro, Mérida', neighborhood = 'Centro' where id = 'osm:node:6223650085';
update public.cafes set nombre = 'Marago Coffee', address = 'Marago Coffee, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:12771231803';
update public.cafes set nombre = 'zitto', address = 'zitto, Calle 61, Mérida, Yucatán, 97169, México', neighborhood = 'Mérida' where id = 'osm:node:4381762591';
update public.cafes set nombre = 'Silvestre Café Galería', address = 'Calle 61 433', neighborhood = 'Centro' where id = 'osm:node:13844973201';
update public.cafes set nombre = 'Café La Habana', address = 'Calle 59 62, Mérida', neighborhood = 'Centro' where id = 'osm:way:699554845';
update public.cafes set nombre = 'Cafetería ENES Mérida', address = 'Enfermería ENES-Mérida, Carretera Mérida - Tetiz, Ucú, Yucatán, 97357, México', neighborhood = neighborhood where id = 'osm:way:1055765846';
update public.cafes set nombre = 'Cafeteria UPY', address = 'Cafeteria UPY, Carretera Mérida - Tetiz, Ucú, Yucatán, 97357, México', neighborhood = neighborhood where id = 'osm:way:1248863080';
update public.cafes set nombre = 'Churrería Don Porfirio', address = 'Churrería Don Porfirio, Av Mérida 2000, Mérida, Yucatán, 97226, México', neighborhood = 'Mérida' where id = 'osm:node:12758737616';
update public.cafes set nombre = 'Café Espiral', address = 'Café Espiral, Calle 5-E, Mérida, Yucatán, 97217, México', neighborhood = 'Mérida' where id = 'osm:node:5112149460';
update public.cafes set nombre = 'Cielito Lindo', address = 'Cielito Lindo, Calle 60, Mérida, Yucatán, 97229, México', neighborhood = 'Mérida' where id = 'osm:node:12200840339';
update public.cafes set nombre = 'La Cata Bakery & Coffee', address = 'La Cata Bakery & Coffee, Avenida Alfredo Barrera Vazquez, Mérida, Yucatán, 97229, México', neighborhood = 'Mérida' where id = 'osm:node:12596310641';
update public.cafes set nombre = 'Coffee Brew Lab SCR', address = 'Calle 36 153, San Damián, Mérida', neighborhood = 'San Damián' where id = 'osm:node:13024850769';
update public.cafes set nombre = 'Starbucks', address = '59-a, Mérida', neighborhood = 'Caucel' where id = 'osm:way:1245607118';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Calle 21, Mérida, Yucatán, 97229, México', neighborhood = 'Mérida' where id = 'osm:way:1421078056';
update public.cafes set nombre = 'Manier Café', address = 'Calle 57 582C', neighborhood = 'Centro' where id = 'osm:node:12437469922';
update public.cafes set nombre = 'Café Voltaire', address = 'Café Voltaire, Calle 72, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:6898349785';
update public.cafes set nombre = 'Bengal Kaffehaus', address = 'Calle 60', neighborhood = 'Centro' where id = 'osm:node:4085361694';
update public.cafes set nombre = 'Neek''Ich Organic Juice Bar', address = 'Neek''Ich Organic Juice Bar, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:5063087717';
update public.cafes set nombre = 'Bengala Kaffeehaus', address = 'Calle 60 53, Mérida', neighborhood = 'Centro' where id = 'osm:node:5310352121';
update public.cafes set nombre = 'Organico', address = 'Organico, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:5432506022';
update public.cafes set nombre = 'Bendito Café', address = 'Calle 55 461C', neighborhood = 'Centro' where id = 'osm:node:5501740722';
update public.cafes set nombre = 'Voltacafé', address = 'Voltacafé, Calle 53, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:9356750317';
update public.cafes set nombre = 'Café Chuc - Tradición Yucateca', address = 'Calle 60 465, Mérida', neighborhood = 'Centro' where id = 'osm:node:9583751917';
update public.cafes set nombre = 'Café Lucy', address = 'Café Lucy, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:12549582601';
update public.cafes set nombre = 'Café Riqueza', address = 'Café Riqueza, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:12629392324';
update public.cafes set nombre = 'White Paper House', address = 'Calle 53 502N, Centro, Mérida', neighborhood = 'Centro' where id = 'osm:node:13048692667';
update public.cafes set nombre = 'Zynergia', address = 'Zynergia, Calle 58, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:13672001001';
update public.cafes set nombre = 'Sempere', address = 'Calle 62 479', neighborhood = 'Centro' where id = 'osm:node:13672007202';
update public.cafes set nombre = 'Tinoc Café', address = 'Calle 58 444, Mérida', neighborhood = 'Centro' where id = 'osm:node:14007740426';
update public.cafes set nombre = 'Arista Barista', address = 'Arista Barista, Calle 54, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:10584314825';
update public.cafes set nombre = 'Café Crème', address = 'Calle 41 386b', neighborhood = 'Centro' where id = 'osm:node:4213559290';
update public.cafes set nombre = 'Blue Bag Coffee Shop', address = 'Blue Bag Coffee Shop, Calle 66, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:6040037888';
update public.cafes set nombre = 'Café del Sol', address = 'Calle 47', neighborhood = 'Centro' where id = 'osm:node:7114661578';
update public.cafes set nombre = 'Health Ha', address = 'Health Ha, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:9859052695';
update public.cafes set nombre = 'Café La Habana', address = 'Café La Habana, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:12543063904';
update public.cafes set nombre = 'La 60 Café Atelier', address = 'La 60 Café Atelier, Calle 60, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:13012312498';
update public.cafes set nombre = 'Dulcería y Sorbetería Colón', address = 'Dulcería y Sorbetería Colón, Paseo de Montejo, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:4384694190';
update public.cafes set nombre = 'Pistache', address = 'Pistache, Paseo de Montejo, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:4584167894';
update public.cafes set nombre = 'Impala', address = 'Impala, Calle 47, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:4835220021';
update public.cafes set nombre = 'Márago Coffee', address = 'Márago Coffee, Paseo Montejo, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:7107954328';
update public.cafes set nombre = 'Café Cafico', address = 'Café Cafico, Calle 58, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:10553619151';
update public.cafes set nombre = 'Baretto - Espresso House', address = 'Baretto - Espresso House, Corredor Turístico Gastronómico, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:node:12581598271';
update public.cafes set nombre = 'Clandestino', address = 'Paseo de Montejo 468', neighborhood = 'Centro' where id = 'osm:node:13598581201';
update public.cafes set nombre = 'De la Reina Roja Café', address = 'De la Reina Roja Café, Circuito Morado, Col. Ferrocarrilera Hector Victoria Aguilar, Centro, Mérida, Yucatán, 97150, México', neighborhood = 'Col. Ferrocarrilera Hector Victoria Aguilar' where id = 'osm:node:12210733051';
update public.cafes set nombre = 'Te Invoco Y Suspiro Café', address = 'Te Invoco Y Suspiro Café, Circuito Morado, Col. Ferrocarrilera Hector Victoria Aguilar, Centro, Mérida, Yucatán, 97150, México', neighborhood = 'Col. Ferrocarrilera Hector Victoria Aguilar' where id = 'osm:node:12210733057';
update public.cafes set nombre = 'Bejar Coffee', address = 'Bejar Coffee, Circuito Morado, Col. Ferrocarrilera Hector Victoria Aguilar, Centro, Mérida, Yucatán, 97150, México', neighborhood = 'Col. Ferrocarrilera Hector Victoria Aguilar' where id = 'osm:node:12210733069';
update public.cafes set nombre = 'Abuelo Guillén', address = 'Abuelo Guillén, Circuito Morado, Col. Ferrocarrilera Hector Victoria Aguilar, Centro, Mérida, Yucatán, 97150, México', neighborhood = 'Col. Ferrocarrilera Hector Victoria Aguilar' where id = 'osm:node:12210733075';
update public.cafes set nombre = 'Relato', address = 'Relato, Circuito Morado, Col. Ferrocarrilera Hector Victoria Aguilar, Centro, Mérida, Yucatán, 97150, México', neighborhood = 'Col. Ferrocarrilera Hector Victoria Aguilar' where id = 'osm:node:12210733078';
update public.cafes set nombre = 'La Cafe de la Uno', address = 'La Cafe de la Uno, Calle 39-B, Fraccionamiento El Fénix, Mérida, Yucatán, 97155, México', neighborhood = 'Fraccionamiento El Fénix' where id = 'osm:node:11957748516';
update public.cafes set nombre = 'JC''s Tree Coffee', address = 'JC''s Tree Coffee, Calle 39, Fracc. Arboledas, Mérida, Yucatán, 97150, México', neighborhood = 'Fracc. Arboledas' where id = 'osm:node:12198320258';
update public.cafes set nombre = 'Italian Coffee', address = 'Italian Coffee, Calle 10, Mérida, Yucatán, 97158, México', neighborhood = 'Mérida' where id = 'osm:node:12349511638';
update public.cafes set nombre = 'Taco City Café', address = 'Taco City Café, Circuito Colonias, Fraccionamiento El Fénix, Mérida, Yucatán, 97159, México', neighborhood = 'Fraccionamiento El Fénix' where id = 'osm:node:12349511662';
update public.cafes set nombre = 'Blue Bag coffee', address = 'Calle 55 543, Santiago, Merida', neighborhood = 'Santiago' where id = 'osm:node:10608061457';
update public.cafes set nombre = 'Manga-Jō Café', address = 'Calle 20 335A', neighborhood = 'Mérida' where id = 'osm:node:11660875569';
update public.cafes set nombre = 'Uj Cafetería', address = 'Uj Cafetería, Calle 29, Mérida, Yucatán, 97127, México', neighborhood = 'Mérida' where id = 'osm:node:4835385923';
update public.cafes set nombre = 'La Vía', address = 'La Vía, Calle 21, Mérida, Yucatán, 97127, México', neighborhood = 'Mérida' where id = 'osm:node:2303170293';
update public.cafes set nombre = 'The Italian Coffe Factory', address = 'The Italian Coffe Factory, Calle 24, Colonia México, Mérida, Yucatán, 97125, México', neighborhood = 'Colonia México' where id = 'osm:node:5025946224';
update public.cafes set nombre = 'Café Louvre', address = 'Avenida Jose Diaz Bolio 75, Mérida', neighborhood = 'Colonia México' where id = 'osm:node:4334764676';
update public.cafes set nombre = 'Italian Coffe', address = 'Italian Coffe, Avenida Tecnológico, Mérida, Yucatán, 97111, México', neighborhood = 'Mérida' where id = 'osm:node:2028735442';
update public.cafes set nombre = 'VIP''s', address = 'VIP''s, Calle 1, Colonia Gonzalo Guerrero, Mérida, Yucatán, 97118, México', neighborhood = 'Colonia Gonzalo Guerrero' where id = 'osm:node:2124462124';
update public.cafes set nombre = 'T-bar', address = 'T-bar, Avenida Andrés García Lavín, San Antonio Cucul, Mérida, Yucatán, 97117, México', neighborhood = 'San Antonio Cucul' where id = 'osm:node:12580931388';
update public.cafes set nombre = 'Ceci Medina', address = 'Ceci Medina, Calle 30, San Antonio Cucul, Mérida, Yucatán, 97117, México', neighborhood = 'San Antonio Cucul' where id = 'osm:node:12580931430';
update public.cafes set nombre = 'Dunkin''', address = 'Avenida Felipe Carrillo Puerto', neighborhood = 'Mérida' where id = 'osm:node:13428400501';
update public.cafes set nombre = 'El Negrito', address = 'El Negrito, Avenida Rita Cetina Gutiérrez, Mérida, Yucatán, 17144, México', neighborhood = 'Mérida' where id = 'osm:node:12198109466';
update public.cafes set nombre = 'Good Tea', address = 'Good Tea, Avenida Correa Rachó, Mérida, Yucatán, 97135, México', neighborhood = 'Mérida' where id = 'osm:node:12580931350';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Avenida Correa Rachó, Mérida, Yucatán, 97135, México', neighborhood = 'Mérida' where id = 'osm:node:12580931352';
update public.cafes set nombre = 'Yolo Coffee', address = 'Yolo Coffee, Avenida José Vasconcelos, Jardines de Vista Alegre II, Mérida, Yucatán, 97133, México', neighborhood = 'Jardines de Vista Alegre II' where id = 'osm:node:12586258807';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Avenida Cámara de Comercio, Fraccionamiento Montereal, Mérida, Yucatán, 97139, México', neighborhood = 'Fraccionamiento Montereal' where id = 'osm:node:6245876544';
update public.cafes set nombre = 'Café Lote Único', address = 'Café Lote Único, Calle 16, Fraccionamiento Residencial Cámara de Comercio Norte, Mérida, Yucatán, 97133, México', neighborhood = 'Fraccionamiento Residencial Cámara de Comercio Norte' where id = 'osm:node:12580931353';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Calle 24, Fraccionamiento Altabrisa, Mérida, Yucatán, 97133, México', neighborhood = 'Fraccionamiento Altabrisa' where id = 'osm:node:1625735022';
update public.cafes set nombre = 'Mi Viejo Molino', address = 'Mi Viejo Molino, Calle 24, Mérida, Yucatán, 97134, México', neighborhood = 'Mérida' where id = 'osm:node:1625735024';
update public.cafes set nombre = 'Maiz Candela y Cilantro', address = 'Maiz Canela y Cilantro, Calle 55, Centro, Mérida, Yucatán, 97000, México', neighborhood = 'Centro' where id = 'osm:way:1248815305';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Paseo Montejo, Centro, Mérida, Yucatán, 97050, México', neighborhood = 'Centro' where id = 'osm:way:1272145503';
update public.cafes set nombre = 'Midna´s Frappé  (Suc. Nueva Mayapan)', address = '43 536-B, Merida', neighborhood = 'Mérida' where id = 'osm:way:1177973219';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Calle 20, Colonia México, Mérida, Yucatán, 97125, México', neighborhood = 'Colonia México' where id = 'osm:way:1376566053';
update public.cafes set nombre = 'Juan Valdez Café', address = 'Juan Valdez Café, Calle 47 Diagonal, Fraccionamiento San Ramón, Mérida, Yucatán, 97117, México', neighborhood = 'Fraccionamiento San Ramón' where id = 'osm:way:1359967096';
update public.cafes set nombre = 'Pastelicioso Gourmet', address = 'Calle 18 232', neighborhood = 'Fraccionamiento Vista Alegre Norte' where id = 'osm:node:5541593323';
update public.cafes set nombre = 'Tbar', address = 'Tbar, Avenida Yucatán, Mérida, Yucatán, 97138, México', neighborhood = 'Mérida' where id = 'osm:node:13336396158';
update public.cafes set nombre = 'Alma cafe MID', address = 'calle 113 entre 146 y 148 Fraccionamiento los heroes Plaza Heroes, 97306 Mérida, Yuc., Mérida , Yucatan', neighborhood = 'Fraccionamiento Los Heroes' where id = 'osm:node:8986763660';
update public.cafes set nombre = 'Midna´s Frappe', address = 'Calle 51 287, Kanasín', neighborhood = 'Kanasín' where id = 'osm:way:1177972986';
update public.cafes set nombre = 'Italian Coffee', address = 'Italian Coffee, Calle 51-A, Mérida, Yucatán, 97203, México', neighborhood = 'Mérida' where id = 'osm:node:2026936989';
update public.cafes set nombre = 'Cafeteria Fiuady', address = 'Cafeteria Fiuady, Calle 85, Dzitya Poligono Chuburna, Mérida, Yucatán, 97110, México', neighborhood = 'Dzitya Poligono Chuburna' where id = 'osm:way:368527504';
update public.cafes set nombre = 'Mi Viejo Molino', address = 'Mi Viejo Molino, Avenida Marcelino Champagnat, Mérida, Yucatán, 97118, México', neighborhood = 'Mérida' where id = 'osm:node:2026898898';
update public.cafes set nombre = 'Rosquillas & Coffee', address = 'Rosquillas & Coffee, Calle 41, Colonia Revolución, Sodzil Norte, Mérida, Yucatán, 92704, México', neighborhood = 'Colonia Revolución' where id = 'osm:node:6652951676';
update public.cafes set nombre = 'Segafredo', address = 'Segafredo, Calle 41, Colonia Revolución, Sodzil Norte, Mérida, Yucatán, 92704, México', neighborhood = 'Colonia Revolución' where id = 'osm:node:6652951681';
update public.cafes set nombre = 'La Crepería', address = 'La Crepería, Calle 41, Colonia Revolución, Sodzil Norte, Mérida, Yucatán, 92704, México', neighborhood = 'Colonia Revolución' where id = 'osm:node:6652960511';
update public.cafes set nombre = 'Starbucks', address = 'Gonzalo Guerrero', neighborhood = 'Fraccionamiento Gonzalo Guerrero' where id = 'osm:node:2028779188';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Calle 75, Montes de Amé, Mérida, Yucatán, 97118, México', neighborhood = 'Montes de Amé' where id = 'osm:node:12345230637';
update public.cafes set nombre = 'Agua de Menta', address = 'Agua de Menta, Calle 36 Diagonal, Fraccionamiento Xaman-Tan, Mérida, Yucatán, 97113, México', neighborhood = 'Fraccionamiento Xaman-Tan' where id = 'osm:node:12588854592';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, 185, Calle 61, Fraccionamiento Villareal, Mérida, Yucatán, 97113, México', neighborhood = 'Fraccionamiento Villareal' where id = 'osm:node:12345212847';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Calle 60, Colonia Xcumpich, Sodzil Norte, Mérida, Yucatán, 97110, México', neighborhood = 'Colonia Xcumpich' where id = 'osm:node:6601491204';
update public.cafes set nombre = 'Starbucks', address = 'Starbucks, Calle 41, Colonia Xcumpich, Sodzil Norte, Mérida, Yucatán, 92704, México', neighborhood = 'Colonia Xcumpich' where id = 'osm:node:13873881018';
update public.cafes set nombre = 'Panarelo', address = 'Panarelo, s/n, Pasillo principal, Sodzil Norte, Mérida, Yucatán, 97300, México', neighborhood = 'Sodzil Norte' where id = 'osm:node:12911209279';
update public.cafes set nombre = 'La cafe', address = 'La cafe, s/n, Entrada principal, Sodzil Norte, Mérida, Yucatán, 97300, México', neighborhood = 'Sodzil Norte' where id = 'osm:node:12911209280';
update public.cafes set nombre = 'cafelia', address = 'Calle 22, Cholul', neighborhood = 'Cholul' where id = 'osm:node:13302914043';
update public.cafes set neighborhood = 'Ucú' where id in ('osm:way:1055765846', 'osm:way:1248863080');
